Updated action

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -1,36 +1,29 @@
-# This is a basic workflow to help you get started with Actions
 
-name: CI
+name: Check for "latest" SQL File
 
-# Controls when the workflow will run
-on:
-  # Triggers the workflow on push or pull request events but only for the "main" branch
-  push:
-    branches: [ "main" ]
+on: 
   pull_request:
-    branches: [ "main" ]
+    branches:
+      - main
 
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "build"
-  build:
-    # The type of runner that the job will run on
+  check-latest-sql:
     runs-on: ubuntu-latest
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v4
+      - name: Checkout repository
+        uses: actions/checkout@v2
 
-      # Runs a single command using the runners shell
-      - name: Run a one-line script
-        run: echo Hello, world!
-
-      # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
+      - name: Check for "latest" SQL File
+        id: check-latest-sql
         run: |
-          echo Add other actions to build,
-          echo test, and deploy your project.
+          if ls csr/db/branchchanges/latest*.sql 1> /dev/null 2>&1; then
+            echo "Error: SQL file containing 'latest' found in branchchanges folder."
+            echo "Please run dev -rp <branchname> before merging to main."
+            exit 1
+          else
+            echo "No 'latest' SQL file found. Proceeding with the pull request."
+          fi
